# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "96b5ec3c0cdf81552a577ceab5710818"
name = "Billing-test"
handle = "billing-test-34"
application_url = "https://arbor-called-sk-width.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "karan-working.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://arbor-called-sk-width.trycloudflare.com/auth/callback",
  "https://arbor-called-sk-width.trycloudflare.com/auth/shopify/callback",
  "https://arbor-called-sk-width.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

[pos]
embedded = false
